import pyodbc
import pandas as pd

# -------- CONNECTION --------
conn = pyodbc.connect(
    'DRIVER={ODBC Driver 18 for SQL Server};'
    'SERVER=142.79.224.75,21443;'
    'DATABASE=GreenTransSugamParivahan;'
    'UID=data_analytics;'
    'PWD=User@1234;'
    'Encrypt=yes;'
    'TrustServerCertificate=yes;'
)

cursor = conn.cursor()

# -------- FULL QUERY --------
query = """
SET NOCOUNT ON;
DECLARE @ORGCODE VARCHAR(3) = '521'

DECLARE @FROM2425 DATE = '2024-04-01'
DECLARE @TO2425   DATE = '2025-03-31'

DECLARE @FROM2526 DATE = '2025-03-15'
DECLARE @TO2526   DATE = '2026-03-14'
DECLARE @DIVISOR FLOAT = 1200000

IF OBJECT_ID('tempdb..#PNL2425') IS NOT NULL DROP TABLE #PNL2425
SELECT 
    BRANCHCODE,
    GRNO,
    SUM(FREIGHT)/@Divisor AS FREIGHT,
    SUM((FREIGHT+DELIVERYINCOME+ADDITIONALFREIGHT+OTHERINCOME)-EXPENSE)/@Divisor AS PNL
INTO #PNL2425
FROM DBO.GREENTRANSWEB_GRWISEPNLDETAIL_V7(@ORGCODE,@FROM2425,@TO2425,'')
GROUP BY BRANCHCODE, GRNO

IF OBJECT_ID('tempdb..#PNL2526') IS NOT NULL DROP TABLE #PNL2526
SELECT 
    BRANCHCODE,
    GRNO,
    SUM(FREIGHT)/@Divisor AS FREIGHT,
    SUM((FREIGHT+DELIVERYINCOME+ADDITIONALFREIGHT+OTHERINCOME)-EXPENSE)/@Divisor AS PNL
INTO #PNL2526
FROM DBO.GREENTRANSWEB_GRWISEPNLDETAIL_V7(@ORGCODE,@FROM2526,@TO2526,'')
GROUP BY BRANCHCODE, GRNO


-- ================= OVERHEAD =================
-- ===================== 2526 =====================
IF OBJECT_ID('tempdb..#OH2526') IS NOT NULL 
    DROP TABLE #OH2526;

SELECT 
    V.BRANCHCODE,
    ISNULL(SUM(V.NETAMT), 0) / @Divisor AS NETAMT
INTO #OH2526
FROM 
(
    -- ================= SALARY =================
    SELECT 
        SS.BRANCHCODE,
        SUM(SS.NETAMT) AS NETAMT
    FROM 
    (
        SELECT 
            SD.BRANCHCODE,
            CAST(
                SUM(SD.EAMOUNT) 
                + IIF(ESI.CNTR = 0, 0, SUM(SD.EAMOUNT - SD.PFAMOUNT) * 3.25 / 100)
            AS NUMERIC(12,2)) AS NETAMT
        FROM VIEWSALARYFORBRANCHPERFORMANCE SD
        
        CROSS APPLY 
        (
            SELECT COUNT(*) AS CNTR
            FROM VIEWSALARY D
            WHERE 
                D.BRANCHCODE = SD.BRANCHCODE
                AND D.EMPLOYEEID = SD.EMPLOYEEID
                AND D.FROMDT BETWEEN @FROM2526 AND @TO2526
                AND D.SALARYVNO IS NOT NULL
                AND D.SALARYCATEGORY = 'S'
                AND D.SALARYHEADID = 9
        ) ESI

        WHERE 
            SD.FROMDT BETWEEN @FROM2526 AND @TO2526
            AND SD.SALARYVNO IS NOT NULL
            AND SD.SALARYCATEGORY = 'S'

        GROUP BY 
            SD.BRANCHCODE, 
            ESI.CNTR
    ) SS
    GROUP BY SS.BRANCHCODE

    UNION ALL

    -- ================= GODOWN RENT =================
    SELECT 
        H.BRANCHCODE,
        SUM(D.AMOUNT) AS NETAMT
    FROM PURCHASEMRNDETAIL D WITH (NOLOCK)
    INNER JOIN PURCHASEMRNHEAD H WITH (NOLOCK) 
        ON H.MRNID = D.MRNID
    WHERE 
        D.ITEMCODE = '30'
        AND H.CANCEL <> 'Y'
        AND H.VNO IS NOT NULL
        AND H.FROMDT BETWEEN @FROM2526 AND @TO2526
        AND H.TODT BETWEEN @FROM2526 AND @TO2526
    GROUP BY H.BRANCHCODE

    UNION ALL

    -- ================= VOUCHER EXP =================
    SELECT 
        VM.BRANCHCODE,
        SUM(VM.DRAMOUNT - VM.CRAMOUNT) AS NETAMT
    FROM VIEWVOUCHER VM
    INNER JOIN VIEWLEDGER L 
        ON L.LEDCODE = VM.LEDCODE
    WHERE 
        VM.VDATE BETWEEN @FROM2526 AND @TO2526
        AND L.MAINGRP = 'AM203'
        AND L.LEDCODE <> '0000001172'
    GROUP BY VM.BRANCHCODE

) V
GROUP BY V.BRANCHCODE;



-- ===================== 2425 =====================
IF OBJECT_ID('tempdb..#OH2425') IS NOT NULL 
    DROP TABLE #OH2425;

SELECT 
    V.BRANCHCODE,
    ISNULL(SUM(V.NETAMT), 0) / @Divisor AS NETAMT
INTO #OH2425
FROM 
(
    -- ================= SALARY =================
    SELECT 
        SS.BRANCHCODE,
        SUM(SS.NETAMT) AS NETAMT
    FROM 
    (
        SELECT 
            SD.BRANCHCODE,
            CAST(
                SUM(SD.EAMOUNT) 
                + IIF(ESI.CNTR = 0, 0, SUM(SD.EAMOUNT - SD.PFAMOUNT) * 3.25 / 100)
            AS NUMERIC(12,2)) AS NETAMT
        FROM VIEWSALARYFORBRANCHPERFORMANCE SD
        
        CROSS APPLY 
        (
            SELECT COUNT(*) AS CNTR
            FROM VIEWSALARY D
            WHERE 
                D.BRANCHCODE = SD.BRANCHCODE
                AND D.EMPLOYEEID = SD.EMPLOYEEID
                AND D.FROMDT BETWEEN @FROM2425 AND @TO2425
                AND D.SALARYVNO IS NOT NULL
                AND D.SALARYCATEGORY = 'S'
                AND D.SALARYHEADID = 9
        ) ESI

        WHERE 
            SD.FROMDT BETWEEN @FROM2425 AND @TO2425
            AND SD.SALARYVNO IS NOT NULL
            AND SD.SALARYCATEGORY = 'S'

        GROUP BY 
            SD.BRANCHCODE, 
            ESI.CNTR
    ) SS
    GROUP BY SS.BRANCHCODE

    UNION ALL

    -- ================= GODOWN RENT =================
    SELECT 
        H.BRANCHCODE,
        SUM(D.AMOUNT) AS NETAMT
    FROM PURCHASEMRNDETAIL D WITH (NOLOCK)
    INNER JOIN PURCHASEMRNHEAD H WITH (NOLOCK) 
        ON H.MRNID = D.MRNID
    WHERE 
        D.ITEMCODE = '30'
        AND H.CANCEL <> 'Y'
        AND H.VNO IS NOT NULL
        AND H.FROMDT BETWEEN @FROM2425 AND @TO2425
        AND H.TODT BETWEEN @FROM2425 AND @TO2425
    GROUP BY H.BRANCHCODE

    UNION ALL

    -- ================= VOUCHER EXP =================
    SELECT 
        VM.BRANCHCODE,
        SUM(VM.DRAMOUNT - VM.CRAMOUNT) AS NETAMT
    FROM VIEWVOUCHER VM WITH (NOLOCK)
    INNER JOIN VIEWLEDGER L 
        ON L.LEDCODE = VM.LEDCODE
    WHERE 
        VM.VDATE BETWEEN @FROM2425 AND @TO2425
        AND L.MAINGRP = 'AM203'
        AND L.LEDCODE <> '0000001172'
    GROUP BY VM.BRANCHCODE

) V
GROUP BY V.BRANCHCODE

-- ================= CLAIM =================
IF OBJECT_ID('tempdb..#CLAIM2425') IS NOT NULL DROP TABLE #CLAIM2425
SELECT BRANCHCODE, ISNULL(SUM(DRAMOUNT-CRAMOUNT),0)/@Divisor NETAMT 
INTO #CLAIM2425
FROM VIEWVOUCHER
WHERE VDATE BETWEEN @FROM2425 AND @TO2425
AND LEDCODE='0000001289'
GROUP BY BRANCHCODE

IF OBJECT_ID('tempdb..#CLAIM2526') IS NOT NULL DROP TABLE #CLAIM2526
SELECT BRANCHCODE, ISNULL(SUM(DRAMOUNT-CRAMOUNT),0)/@Divisor NETAMT 
INTO #CLAIM2526
FROM VIEWVOUCHER
WHERE VDATE BETWEEN @FROM2526 AND @TO2526
AND LEDCODE='0000001289'
GROUP BY BRANCHCODE


-- ================= OS =================
IF OBJECT_ID('tempdb..#OS2425') IS NOT NULL DROP TABLE #OS2425
SELECT 
    S.STNCODE AS BRANCHCODE,
    F.NETOUTSTANDING,
    (F.NETOUTSTANDING*1.25/100)/100000 AS OSINTT
INTO #OS2425
FROM STATIONMAST S
CROSS APPLY DBO.GREENTRANSWEB_BRANCHOUTSTANDINGSUMMARY(S.STNCODE,'1980-01-01',@TO2425,@TO2425) F
WHERE S.STNCODE=@ORGCODE

IF OBJECT_ID('tempdb..#OS2526') IS NOT NULL DROP TABLE #OS2526
SELECT 
    S.STNCODE AS BRANCHCODE,
    F.NETOUTSTANDING,
    (F.NETOUTSTANDING*1.25/100)/100000 AS OSINTT
INTO #OS2526
FROM STATIONMAST S
CROSS APPLY DBO.GREENTRANSWEB_BRANCHOUTSTANDINGSUMMARY(S.STNCODE,'1980-01-01',@TO2526,@TO2526) F
WHERE S.STNCODE=@ORGCODE


-- ================= COLLECTION =================
IF OBJECT_ID('tempdb..#COLL2425') IS NOT NULL DROP TABLE #COLL2425
SELECT MR.BRANCHCODE, (ISNULL(SUM(MR.DEPOSITAMOUNT),0)-ISNULL(SUM(REFUND.REFUNDAMT),0))/@Divisor AS COLL
INTO #COLL2425
FROM MRHEAD MR
OUTER APPLY(SELECT CR.BRANCHCODE,ISNULL(CR.REFUNDAMOUNT,0) AS REFUNDAMT
                               FROM CUSTOMERREFUND CR WITH (NOLOCK)
                               WHERE CR.MRNO=MR.MRNO AND CR.CANCEL<>'Y') REFUND
WHERE MRDT BETWEEN @FROM2425 AND @TO2425
AND MR.REVERSEMR<>'Y' AND MR.CANCEL<>'Y' AND MR.CREDITNOTE<>'Y'
GROUP BY MR.BRANCHCODE

IF OBJECT_ID('tempdb..#COLL2526') IS NOT NULL DROP TABLE #COLL2526
SELECT MR.BRANCHCODE, (ISNULL(SUM(MR.DEPOSITAMOUNT),0)-ISNULL(SUM(REFUND.REFUNDAMT),0))/@Divisor AS COLL
INTO #COLL2526
FROM MRHEAD MR
OUTER APPLY(SELECT CR.BRANCHCODE,ISNULL(CR.REFUNDAMOUNT,0) AS REFUNDAMT
                               FROM CUSTOMERREFUND CR WITH (NOLOCK)
                               WHERE CR.MRNO=MR.MRNO AND CR.CANCEL<>'Y') REFUND
WHERE MRDT BETWEEN @FROM2526 AND @TO2526
AND MR.REVERSEMR<>'Y' AND MR.CANCEL<>'Y' AND MR.CREDITNOTE<>'Y'
GROUP BY MR.BRANCHCODE

-- ================= B.DESH =================

IF OBJECT_ID('tempdb..#BD') IS NOT NULL DROP TABLE #BD;

SELECT 
    CN.ORGCODE,
    SUM(CASE 
        WHEN CN.GRDT BETWEEN @FROM2425 AND @TO2425 
        THEN (CN.TAMOUNT - CN.SERVICETAX) / @DIVISOR
        ELSE 0 
    END) AS BD_2425,

    SUM(CASE 
        WHEN CN.GRDT BETWEEN @FROM2526 AND @TO2526 
        THEN (CN.TAMOUNT - CN.SERVICETAX) / @DIVISOR
        ELSE 0 
    END) AS BD_2526

INTO #BD
FROM CNMT CN
INNER JOIN STATIONMAST DST ON DST.STNCODE = CN.DESTCODE
WHERE 
    CN.GRDT BETWEEN @FROM2425 AND @TO2526
    AND CN.GRTYPE <> 'N'
    AND (
        DST.COUNTRY = 'BANGLADESH' 
        OR DST.STNNAME IN ('PETRAPOLE', 'MYMENSINGH')
    )
GROUP BY CN.ORGCODE;

-- ================= BHUTAN =================

IF OBJECT_ID('tempdb..#BHU') IS NOT NULL DROP TABLE #BHU;

SELECT 
    CN.ORGCODE,
    SUM(CASE 
        WHEN CN.GRDT BETWEEN @FROM2425 AND @TO2425 
        THEN (CN.TAMOUNT - CN.SERVICETAX) / @DIVISOR
        ELSE 0 
    END) AS BHU_2425,

    SUM(CASE 
        WHEN CN.GRDT BETWEEN @FROM2526 AND @TO2526 
        THEN (CN.TAMOUNT - CN.SERVICETAX) / @DIVISOR
        ELSE 0 
    END) AS BHU_2526

INTO #BHU
FROM CNMT CN
INNER JOIN STATIONMAST DST ON DST.STNCODE = CN.DESTCODE
WHERE 
    CN.GRDT BETWEEN @FROM2425 AND @TO2526
    AND CN.GRTYPE <> 'N'
    AND DST.COUNTRY = 'BHUTAN' 
GROUP BY CN.ORGCODE;

-- ================= Express =================

IF OBJECT_ID('tempdb..#EXPRESS') IS NOT NULL 
    DROP TABLE #EXPRESS;

SELECT 
    COALESCE(DELIVERY.destcode, BOOKING.orgcode) AS ORGCODE,
    
    ISNULL(ROUND(SUM(ISNULL(BOOKING.FY24_25,0) + ISNULL(DELIVERY.FY24_25,0)), 2), 0) AS EXP_2425,
    ISNULL(ROUND(SUM(ISNULL(BOOKING.FY25_26,0) + ISNULL(DELIVERY.FY25_26,0)), 2), 0) AS EXP_2526

INTO #EXPRESS

FROM 
(
    -- BOOKING (UNCHANGED)
    SELECT 
        CN.ORGCODE,

        ROUND(SUM(CASE 
            WHEN CN.GRDT BETWEEN @FROM2425 AND @TO2425 
            THEN ISNULL(CN.TAMOUNT,0) - ISNULL(CN.SERVICETAX,0) 
            ELSE 0 END) / 1200000, 2) AS FY24_25,

        ROUND(SUM(CASE 
            WHEN CN.GRDT BETWEEN @FROM2526 AND @TO2526 
            THEN ISNULL(CN.TAMOUNT,0) - ISNULL(CN.SERVICETAX,0) 
            ELSE 0 END) / 1200000, 2) AS FY25_26

    FROM GREENTRANSSUGAMEXPRESS..CNMT CN
    INNER JOIN STATIONMAST ORG ON ORG.STNCODE = CN.ORGCODE
    WHERE CN.GRDT BETWEEN @FROM2425 AND @TO2526
      AND ISNULL(CAST(CN.GRTYPE AS VARCHAR), '') <> 'N'
    GROUP BY CN.ORGCODE
) BOOKING

FULL OUTER JOIN 
(
    -- DELIVERY (UNCHANGED)
    SELECT 
        CASE
            WHEN COALESCE(MRG.STNCODE, DEST.STNCODE) = '704' THEN '602'
            WHEN COALESCE(MRG.STNCODE, DEST.STNCODE) = '705' THEN '601'
            WHEN COALESCE(MRG.STNCODE, DEST.STNCODE) = '708' THEN '603'
            WHEN COALESCE(MRG.STNCODE, DEST.STNCODE) = '712' THEN '171'
            WHEN COALESCE(MRG.STNCODE, DEST.STNCODE) = '709' THEN '607'
            ELSE COALESCE(MRG.STNCODE, DEST.STNCODE)
        END AS destcode,

        ROUND(SUM(CASE 
            WHEN CN.GRDT BETWEEN @FROM2425 AND @TO2425 
            THEN ISNULL(CN.TAMOUNT,0) - ISNULL(CN.SERVICETAX,0) 
            ELSE 0 END) / 1200000, 2) AS FY24_25,

        ROUND(SUM(CASE 
            WHEN CN.GRDT BETWEEN @FROM2526 AND @TO2526 
            THEN ISNULL(CN.TAMOUNT,0) - ISNULL(CN.SERVICETAX,0) 
            ELSE 0 END) / 1200000, 2) AS FY25_26

    FROM GREENTRANSSUGAMEXPRESS..CNMT CN
    INNER JOIN STATIONMAST DEST ON DEST.STNCODE = CN.DESTCODE
    LEFT JOIN STATIONMAST MRG ON MRG.STNCODE = DEST.MERGESTNCODE
    WHERE CN.GRDT BETWEEN @FROM2425 AND @TO2526
      AND ISNULL(CAST(CN.GRTYPE AS VARCHAR), '') <> 'N'
    GROUP BY COALESCE(MRG.STNcode, DEST.stncode)
) DELIVERY

ON DELIVERY.destcode = BOOKING.orgcode

GROUP BY 
    COALESCE(DELIVERY.destcode, BOOKING.orgcode);


-- ================= MAIN =================
SELECT 
XY.ZONENAME, XY.CIRCLE, XY.ORGCODE, XY.BRANCH, XY.[LTL 24-25], XY.[LTL 25-26], XY.[LTL DIFF], XY.[LTL DIFF %], NULL AS RATING,null as Weightage,

       XY.[FTL 24-25], XY.[FTL 25-26], XY.[FTL DIFF], XY.[FTL DIFF %], NULL AS RATING,null as Weightage,
       XY.[GP 24-25], XY.[GP 24-25 %], XY.[GP 25-26], XY.[GP 25-26 %], XY.[GP DIFF], XY.[GP DIFF %], NULL AS RATING,null as Weightage,

-- NP
ROUND(ISNULL(XY.[GP 24-25],0) - (ISNULL(OH2425.NETAMT,0)+ISNULL(XY.[2425 BK 6%],0)+ISNULL(OS2425.OSINTT,0)+ISNULL(CLAIM2425.NETAMT,0)),2) AS NP_2425,

ROUND(ISNULL(XY.[GP 25-26],0) - (ISNULL(OH2526.NETAMT,0)+ISNULL(XY.[2526 BK 6%],0)+ISNULL(OS2526.OSINTT,0)+ISNULL(CLAIM2526.NETAMT,0)),2) AS NP_2526,

ROUND(ISNULL(XY.[GP 25-26],0)-(ISNULL(OH2526.NETAMT,0)+ISNULL(XY.[2425 BK 6%],0)+ISNULL(OS2526.OSINTT,0)+ISNULL(CLAIM2526.NETAMT,0)) - 
             (ISNULL(XY.[GP 24-25],0)-(ISNULL(OH2425.NETAMT,0)+ISNULL(XY.[2425 BK 6%],0)+ISNULL(OS2425.OSINTT,0)+ISNULL(CLAIM2425.NETAMT,0))),2) AS 'NP DIFF',

       (ISNULL(XY.[GP 25-26],0)-(ISNULL(OH2526.NETAMT,0)+ISNULL(XY.[2526 BK 6%],0)+ISNULL(OS2526.OSINTT,0)+ISNULL(CLAIM2526.NETAMT,0)) - 
       (ISNULL(XY.[GP 24-25],0)-(ISNULL(OH2425.NETAMT,0)+ISNULL(XY.[2425 BK 6%],0)+ISNULL(OS2425.OSINTT,0)+ISNULL(CLAIM2425.NETAMT,0))))
       *100/NULLIF((ISNULL(XY.[GP 24-25],0)-(ISNULL(OH2425.NETAMT,0)+ISNULL(XY.[2425 BK 6%],0)+ISNULL(OS2425.OSINTT,0)+ISNULL(CLAIM2425.NETAMT,0))),0) AS 'NP DIFF %' 

---B.DESH
,ROUND(ISNULL(BD.BD_2425,0),2) AS [BD 24-25]
,ROUND(ISNULL(BD.BD_2526,0),2) AS [BD 25-26]
,ROUND(ISNULL(BD.BD_2526,0) - ISNULL(BD.BD_2425,0),2) AS [BD DIFF]
,ROUND(
    (ISNULL(BD.BD_2526,0) - ISNULL(BD.BD_2425,0)) * 100 
    / NULLIF(ISNULL(BD.BD_2425,0),0)
,2) AS [BD DIFF %]

---BHUTAN
,ROUND(ISNULL(BHU.BHU_2425,0),2) AS [BHU 24-25]
,ROUND(ISNULL(BHU.BHU_2526,0),2) AS [BHU 25-26]
,ROUND(ISNULL(BHU.BHU_2526,0) - ISNULL(BHU.BHU_2425,0),2) AS [BHU DIFF]
,ROUND(
    (ISNULL(BHU.BHU_2526,0) - ISNULL(BHU.BHU_2425,0)) * 100 
    / NULLIF(ISNULL(BHU.BHU_2425,0),0),2) AS [BHU DIFF %]

---Express
,ROUND(ISNULL(EXP.EXP_2425,0),2) AS [EXPRESS 24-25]
,ROUND(ISNULL(EXP.EXP_2526,0),2) AS [EXPRESS 25-26]
,ROUND(ISNULL(EXP.EXP_2526,0) - ISNULL(EXP.EXP_2425,0),2) AS [EXPRESS DIFF]
,ROUND(
    (ISNULL(EXP.EXP_2526,0) - ISNULL(EXP.EXP_2425,0)
 ) *100 / NULLIF(ISNULL(EXP.EXP_2425,0),0),2) AS [EXPRESS DIFF %]

-- OS
--ROUND(OS2425.NETOUTSTANDING/100000,2) AS '24-25 OS', ROUND(OS2526.NETOUTSTANDING/100000,2) AS '25-26 OS',

-- COLL
--       ROUND(COLL2425.COLL,2) AS '24-25 COLL', ROUND(COLL2526.COLL,2) AS '25-26 COLL',
--       ROUND(ISNULL(COLL2526.COLL,0)-ISNULL(COLL2425.COLL,0),2) AS 'COLL DIFF',
--       ROUND((ISNULL(COLL2526.COLL,0)-ISNULL(COLL2425.COLL,0))*100/NULLIF((ISNULL(COLL2425.COLL,0)),0),2) AS 'COLL DIFF %',
--       NULL AS 'RATING-CCD'


FROM
(
SELECT 
    X.ZONENAME,
    X.HUBNAME AS CIRCLE,
    X.ORGCODE,
    X.BRANCH,

    ROUND(SUM(X.LTL2425),2) AS [LTL 24-25],
    ROUND(SUM(X.LTL2526),2) AS [LTL 25-26],
    ROUND(ISNULL(SUM(X.LTL2526),0)-ISNULL(SUM(X.LTL2425),0),2) AS 'LTL DIFF',
    ROUND((ISNULL(SUM(X.LTL2526),0)-ISNULL(SUM(X.LTL2425),0))*100/NULLIF((ISNULL(SUM(X.LTL2425),0)),0),2) AS 'LTL DIFF %',

    ROUND(SUM(X.FTL2425),2) AS [FTL 24-25],
    ROUND(SUM(X.FTL2526),2) AS [FTL 25-26],

    ROUND(ISNULL(SUM(X.FTL2526),0)-ISNULL(SUM(X.FTL2425),0),2) AS 'FTL DIFF',
    ROUND((ISNULL(SUM(X.FTL2526),0)-ISNULL(SUM(X.FTL2425),0))*100/NULLIF((ISNULL(SUM(X.FTL2425),0)),0),2) AS 'FTL DIFF %',

    ROUND(SUM(X.GP2425),2) AS [GP 24-25],
    ROUND(SUM(X.GP2425)*100/NULLIF(SUM(X.BKG2425),0),2) AS 'GP 24-25 %',
    
    ROUND(SUM(X.GP2526),2) AS [GP 25-26],
    ROUND(SUM(X.GP2526)*100/NULLIF(SUM(X.BKG2526),0),2) AS 'GP 25-26 %',

    ROUND(ISNULL(SUM(X.GP2526),0)-ISNULL(SUM(X.GP2425),0),2) AS 'GP DIFF',
    ROUND((SUM(X.GP2526)*100/NULLIF(SUM(X.BKG2526),0))-(SUM(X.GP2425)*100/NULLIF(SUM(X.BKG2425),0)),2) AS 'GP DIFF %',

    ROUND(ISNULL(SUM(X.BKG2425),0),2)*6/100 AS '2425 BK 6%',
    ROUND(ISNULL(SUM(X.BKG2526),0),2)*6/100 AS '2526 BK 6%'

FROM
(
SELECT 
    CN.ORGCODE,
    ORG.STNNAME AS BRANCH,
    ZONE.ZONENAME,
    ZONE.HUBNAME,

    CASE WHEN CN.GRDT BETWEEN @FROM2425 AND @TO2425 AND CN.FTL<>'Y'
         THEN (CN.TAMOUNT-CN.SERVICETAX)/@Divisor END AS LTL2425,

    CASE WHEN CN.GRDT BETWEEN @FROM2526 AND @TO2526 AND CN.FTL<>'Y'
         THEN (CN.TAMOUNT-CN.SERVICETAX)/@Divisor END AS LTL2526,

    CASE WHEN CN.GRDT BETWEEN @FROM2425 AND @TO2425 AND CN.FTL='Y'
         THEN (CN.TAMOUNT-CN.SERVICETAX)/@Divisor END AS FTL2425,

    CASE WHEN CN.GRDT BETWEEN @FROM2526 AND @TO2526 AND CN.FTL='Y'
         THEN (CN.TAMOUNT-CN.SERVICETAX)/@Divisor END AS FTL2526,

    G2425.PNL AS GP2425,
    G2526.PNL AS GP2526,

    G2425.FREIGHT AS BKG2425,
    G2526.FREIGHT AS BKG2526

FROM CNMT CN
LEFT JOIN STATIONMAST ORG ON ORG.STNCODE=CN.ORGCODE
LEFT JOIN VIEWSTATIONMAST ZONE ON ZONE.STNCODE=CN.ORGCODE
LEFT JOIN #PNL2425 G2425 ON G2425.GRNO=CN.GRNO
LEFT JOIN #PNL2526 G2526 ON G2526.GRNO=CN.GRNO

WHERE CN.ORGCODE=@ORGCODE
) X
GROUP BY X.ZONENAME,X.HUBNAME,X.ORGCODE,X.BRANCH
) XY

LEFT JOIN #OH2425 OH2425 ON OH2425.BRANCHCODE=XY.ORGCODE
LEFT JOIN #OH2526 OH2526 ON OH2526.BRANCHCODE=XY.ORGCODE
LEFT JOIN #CLAIM2425 CLAIM2425 ON CLAIM2425.BRANCHCODE=XY.ORGCODE
LEFT JOIN #CLAIM2526 CLAIM2526 ON CLAIM2526.BRANCHCODE=XY.ORGCODE
LEFT JOIN #OS2425 OS2425 ON OS2425.BRANCHCODE=XY.ORGCODE
LEFT JOIN #OS2526 OS2526 ON OS2526.BRANCHCODE=XY.ORGCODE
LEFT JOIN #COLL2425 COLL2425 ON COLL2425.BRANCHCODE=XY.ORGCODE
LEFT JOIN #COLL2526 COLL2526 ON COLL2526.BRANCHCODE=XY.ORGCODE
LEFT JOIN #BD BD ON BD.ORGCODE = XY.ORGCODE
LEFT JOIN #BHU BHU ON BHU.ORGCODE = XY.ORGCODE
LEFT JOIN #EXPRESS EXP ON EXP.ORGCODE = XY.ORGCODE
"""

# -------- EXECUTE --------
cursor.execute(query)

df = None  # initialize

while True:
    if cursor.description is not None:
        columns = [col[0] for col in cursor.description]
        data = cursor.fetchall()
        df = pd.DataFrame.from_records(data, columns=columns)

    if not cursor.nextset():
        break

if df is not None:
    print(df.head())
else:
    print("No result found")